name: hive_listener
description: A tiny widget to listen hive box changes, using the ValueListenableBuilder with removing unnecessary parts of it, like context and child widget of it.
version: 0.1.0
repository: https://github.com/malibayram91/hive_listener
homepage: https://github.com/malibayram91/hive_listener

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
